import path from 'path';
import chalk from 'chalk';
import webpack from 'webpack';
import WebpackDevServer from 'webpack-dev-server';

import * as config from '../config';
import webpack_config from './webpack.dev.config';

// Create dev-server
const server = new WebpackDevServer(webpack(webpack_config, (err, stats) => {
  if (err) {
    console.info(chalk.white.bgRed(  '              BUILD FAILED               '));
    console.error(err);
  } else {
    console.info(chalk.white.bgGreen('        SERVER STARTED ON PORT %s        '), config.dev_server.port);
  }
}), {
  hot: true,
  lazy: false,
  // quiet: true,
  // noInfo: true,
  stats: {
    colors: true,
    cached: true,
    cachedAssets: true
  },
  historyApiFallback: true,
  contentBase: webpack_config.output.path,
  publicPath: webpack_config.output.publicPath
});

// Enable simple request log
server.use(require('morgan')('dev'));

// Resolve and serve index.html generated by HtmlWebpackPlugin
server.use((req, res, next) => {
  if (req.url !== '/index.html') return next();
  let { fileSystem } = server.middleware;
  let filename = path.resolve(webpack_config.output.path, config.path.html);
  let content = fileSystem.readFileSync(filename);
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Content-Type', 'text/html; charset=UTF-8');
  res.setHeader('Content-Length', content.length);
  res.send(content);
});

// Start dev-server
server.listen(config.dev_server);
